enum TaskParentCategory {
  work,
  education,
  shopping,
  food,
  health,
  fitness,
  travel,
  transportation,
  home,
  finance,
  relationships,
  lifestyle,
  other,
}

enum TaskCategory {
  work,
  meeting,
  presentation,
  email,
  phoneCall,
  project,
  deadline,
  coding,
  bugFix,
  research,
  study,
  homework,
  exam,
  reading,
  writing,
  noteTaking,
  languageLearning,
  school,
  childcare,
  sleep,
  shopping,
  groceries,
  clothesShopping,
  electronicsShopping,
  onlineOrder,
  gift,
  birthday,
  returnItem,
  pickup,
  delivery,
  cooking,
  breakfast,
  lunch,
  dinner,
  restaurant,
  coffee,
  foodOrder,
  mealPrep,
  baking,
  drinks,
  health,
  doctor,
  dentist,
  medicine,
  pharmacy,
  hospital,
  therapy,
  checkup,
  vaccination,
  medicalTest,
  meditation,
  gym,
  running,
  walking,
  cycling,
  swimming,
  yoga,
  workout,
  sport,
  stretching,
  travel,
  flight,
  hotel,
  vacation,
  luggage,
  passport,
  visa,
  tripPlanning,
  sightseeing,
  reservation,
  car,
  carMaintenance,
  carRepair,
  fuel,
  carWash,
  parking,
  publicTransport,
  taxi,
  train,
  driving,
  home,
  cleaning,
  laundry,
  dishes,
  homeRepair,
  gardening,
  furniture,
  moving,
  organizing,
  bills,
  finance,
  payment,
  banking,
  subscription,
  family,
  friends,
  pet,
  entertainment,
  appointment,

  /// Neutral fallback when classification is not confident (`general`).
  other,
}

extension TaskCategoryMetadata on TaskCategory {
  String get storageName => switch (this) {
    TaskCategory.phoneCall => 'phone_call',
    TaskCategory.bugFix => 'bug_fix',
    TaskCategory.noteTaking => 'note_taking',
    TaskCategory.languageLearning => 'language_learning',
    TaskCategory.clothesShopping => 'clothes_shopping',
    TaskCategory.electronicsShopping => 'electronics_shopping',
    TaskCategory.onlineOrder => 'online_order',
    TaskCategory.returnItem => 'return_item',
    TaskCategory.foodOrder => 'food_order',
    TaskCategory.mealPrep => 'meal_prep',
    TaskCategory.medicalTest => 'medical_test',
    TaskCategory.tripPlanning => 'trip_planning',
    TaskCategory.carMaintenance => 'car_maintenance',
    TaskCategory.carRepair => 'car_repair',
    TaskCategory.carWash => 'car_wash',
    TaskCategory.publicTransport => 'public_transport',
    TaskCategory.homeRepair => 'home_repair',
    _ => name,
  };

  TaskParentCategory get parent => switch (index) {
    >= 0 && <= 9 => TaskParentCategory.work,
    >= 10 && <= 19 => TaskParentCategory.education,
    >= 20 && <= 29 => TaskParentCategory.shopping,
    >= 30 && <= 39 => TaskParentCategory.food,
    >= 40 && <= 49 => TaskParentCategory.health,
    >= 50 && <= 59 => TaskParentCategory.fitness,
    >= 60 && <= 69 => TaskParentCategory.travel,
    >= 70 && <= 79 => TaskParentCategory.transportation,
    >= 80 && <= 89 => TaskParentCategory.home,
    >= 90 && <= 93 => TaskParentCategory.finance,
    >= 94 && <= 96 => TaskParentCategory.relationships,
    >= 97 && <= 98 => TaskParentCategory.lifestyle,
    _ => TaskParentCategory.other,
  };
}

final Map<String, TaskCategory> taskCategoryByStorageName = {
  for (final category in TaskCategory.values) category.storageName: category,
};
