import 'package:flutter_icon_park/flutter_icon_park.dart';
import 'package:florien/features/task_icon/domain/task_category.dart';

export 'package:flutter_icon_park/flutter_icon_park.dart' show IconParkData;

/// Single source of truth: [TaskCategory] → IconPark Multi-color icon.
///
/// UI widgets must read icons from here. Do not map icons in screens.
abstract final class TaskIconRegistry {
  static IconParkData iconFor(TaskCategory category) => switch (category) {
    TaskCategory.work => IconPark.briefcase,
    TaskCategory.meeting => IconPark.peoples,
    TaskCategory.presentation => IconPark.ppt,
    TaskCategory.email => IconPark.mail,
    TaskCategory.phoneCall => IconPark.phoneCall,
    TaskCategory.project => IconPark.clipboard,
    TaskCategory.deadline => IconPark.alarmClock,
    TaskCategory.coding => IconPark.codeLaptop,
    TaskCategory.bugFix => IconPark.bug,
    TaskCategory.research => IconPark.search,
    TaskCategory.study => IconPark.degreeHat,
    TaskCategory.homework => IconPark.notebook,
    TaskCategory.exam => IconPark.pencil,
    TaskCategory.reading => IconPark.readBook,
    TaskCategory.writing => IconPark.write,
    TaskCategory.noteTaking => IconPark.notebookAndPen,
    TaskCategory.languageLearning => IconPark.translate,
    TaskCategory.school => IconPark.school,
    TaskCategory.childcare => IconPark.baby,
    TaskCategory.sleep => IconPark.sleep,
    TaskCategory.shopping => IconPark.shoppingBag,
    TaskCategory.groceries => IconPark.shoppingCart,
    TaskCategory.clothesShopping => IconPark.tShirt,
    TaskCategory.electronicsShopping => IconPark.headset,
    TaskCategory.onlineOrder => IconPark.buy,
    TaskCategory.gift => IconPark.gift,
    TaskCategory.birthday => IconPark.birthdayCake,
    TaskCategory.returnItem => IconPark.return_,
    TaskCategory.pickup => IconPark.mallBag,
    TaskCategory.delivery => IconPark.delivery,
    TaskCategory.cooking => IconPark.cooking,
    TaskCategory.breakfast => IconPark.bread,
    TaskCategory.lunch => IconPark.rice,
    TaskCategory.dinner => IconPark.noodles,
    TaskCategory.restaurant => IconPark.forkSpoon,
    TaskCategory.coffee => IconPark.teaDrink,
    TaskCategory.foodOrder => IconPark.hamburger,
    TaskCategory.mealPrep => IconPark.cookingPot,
    TaskCategory.baking => IconPark.cake,
    TaskCategory.drinks => IconPark.cocktail,
    TaskCategory.health => IconPark.health,
    TaskCategory.doctor => IconPark.stethoscope,
    TaskCategory.dentist => IconPark.teeth,
    TaskCategory.medicine => IconPark.pills,
    TaskCategory.pharmacy => IconPark.medicineBottle,
    TaskCategory.hospital => IconPark.hospital,
    TaskCategory.therapy => IconPark.brain,
    TaskCategory.checkup => IconPark.heartRate,
    TaskCategory.vaccination => IconPark.injection,
    TaskCategory.medicalTest => IconPark.microscope,
    TaskCategory.meditation => IconPark.lotus,
    TaskCategory.gym => IconPark.dumbbell,
    TaskCategory.running => IconPark.sport,
    TaskCategory.walking => IconPark.foot,
    TaskCategory.cycling => IconPark.bike,
    TaskCategory.swimming => IconPark.swimmingPool,
    TaskCategory.yoga => IconPark.stretching,
    TaskCategory.workout => IconPark.fitness,
    TaskCategory.sport => IconPark.basketball,
    TaskCategory.stretching => IconPark.stretchingOne,
    TaskCategory.travel => IconPark.world,
    TaskCategory.flight => IconPark.airplane,
    TaskCategory.hotel => IconPark.hotel,
    TaskCategory.vacation => IconPark.beachUmbrella,
    TaskCategory.luggage => IconPark.luggage,
    TaskCategory.passport => IconPark.passport,
    TaskCategory.visa => IconPark.idCardH,
    TaskCategory.tripPlanning => IconPark.mapTwo,
    TaskCategory.sightseeing => IconPark.camera,
    TaskCategory.reservation => IconPark.ticket,
    TaskCategory.car => IconPark.car,
    TaskCategory.carMaintenance => IconPark.tool,
    TaskCategory.carRepair => IconPark.repair,
    TaskCategory.fuel => IconPark.petrol,
    TaskCategory.carWash => IconPark.showerHead,
    TaskCategory.parking => IconPark.parking,
    TaskCategory.publicTransport => IconPark.bus,
    TaskCategory.taxi => IconPark.taxi,
    TaskCategory.train => IconPark.train,
    TaskCategory.driving => IconPark.steeringWheel,
    TaskCategory.home => IconPark.home,
    TaskCategory.cleaning => IconPark.vacuumCleaner,
    TaskCategory.laundry => IconPark.washingMachine,
    TaskCategory.dishes => IconPark.bowl,
    TaskCategory.homeRepair => IconPark.hammerAndAnvil,
    TaskCategory.gardening => IconPark.seedling,
    TaskCategory.furniture => IconPark.sofa,
    TaskCategory.moving => IconPark.truck,
    TaskCategory.organizing => IconPark.categoryManagement,
    TaskCategory.bills => IconPark.bill,
    TaskCategory.finance => IconPark.wallet,
    TaskCategory.payment => IconPark.bankCard,
    TaskCategory.banking => IconPark.bank,
    TaskCategory.subscription => IconPark.cycle,
    TaskCategory.family => IconPark.family,
    TaskCategory.friends => IconPark.everyUser,
    TaskCategory.pet => IconPark.dog,
    TaskCategory.entertainment => IconPark.movie,
    TaskCategory.appointment => IconPark.calendar,
    TaskCategory.other => IconPark.listCheckbox,
  };

  static String iconName(TaskCategory category) => iconFor(category).name;

  static TaskCategory categoryForStorageName(String name) {
    final category = taskCategoryByStorageName[name];
    if (category != null) return category;
    return _legacyStorageNames[name] ?? TaskCategory.other;
  }

  static const _legacyStorageNames = <String, TaskCategory>{
    'task': TaskCategory.other,
    'timer': TaskCategory.deadline,
    'school': TaskCategory.school,
    'menu_book': TaskCategory.reading,
    'work': TaskCategory.work,
    'groups': TaskCategory.meeting,
    'fitness': TaskCategory.gym,
    'directions_run': TaskCategory.running,
    'directions_walk': TaskCategory.walking,
    'restaurant': TaskCategory.restaurant,
    'free_breakfast': TaskCategory.breakfast,
    'cleaning': TaskCategory.cleaning,
    'shopping': TaskCategory.shopping,
    'health': TaskCategory.health,
    'medication': TaskCategory.medicine,
    'code': TaskCategory.coding,
    'bedtime': TaskCategory.sleep,
    'self_improvement': TaskCategory.yoga,
    'lightbulb': TaskCategory.research,
    'slideshow': TaskCategory.presentation,
    'search': TaskCategory.research,
    'movie': TaskCategory.entertainment,
    'directions_car': TaskCategory.car,
    'child_care': TaskCategory.childcare,
    'pets': TaskCategory.pet,
    'yard': TaskCategory.gardening,
    'music': TaskCategory.entertainment,
    'videocam': TaskCategory.entertainment,
    'brush': TaskCategory.writing,
    'water_drop': TaskCategory.cleaning,
  };
}
