import 'package:flutter/material.dart';
import 'package:florien/features/task_icon/domain/task_category.dart';

class TaskIconMapper {
  const TaskIconMapper._();

  static const fallback = Icons.task_alt_rounded;

  static IconData iconFor(TaskCategory category) => switch (category) {
    TaskCategory.work => Icons.work_rounded,
    TaskCategory.meeting => Icons.groups_rounded,
    TaskCategory.presentation => Icons.slideshow_rounded,
    TaskCategory.email => Icons.mail_rounded,
    TaskCategory.phoneCall => Icons.call_rounded,
    TaskCategory.project => Icons.account_tree_rounded,
    TaskCategory.deadline => Icons.event_busy_rounded,
    TaskCategory.coding => Icons.code_rounded,
    TaskCategory.bugFix => Icons.bug_report_rounded,
    TaskCategory.research => Icons.search_rounded,
    TaskCategory.study => Icons.school_rounded,
    TaskCategory.homework => Icons.assignment_rounded,
    TaskCategory.exam => Icons.quiz_rounded,
    TaskCategory.reading => Icons.menu_book_rounded,
    TaskCategory.writing => Icons.edit_rounded,
    TaskCategory.noteTaking => Icons.sticky_note_2_rounded,
    TaskCategory.languageLearning => Icons.translate_rounded,
    TaskCategory.school => Icons.backpack_rounded,
    TaskCategory.childcare => Icons.child_care_rounded,
    TaskCategory.sleep => Icons.bedtime_rounded,
    TaskCategory.shopping => Icons.shopping_bag_rounded,
    TaskCategory.groceries => Icons.local_grocery_store_rounded,
    TaskCategory.clothesShopping => Icons.checkroom_rounded,
    TaskCategory.electronicsShopping => Icons.headphones_rounded,
    TaskCategory.onlineOrder => Icons.shopping_cart_rounded,
    TaskCategory.gift => Icons.card_giftcard_rounded,
    TaskCategory.birthday => Icons.cake_rounded,
    TaskCategory.returnItem => Icons.assignment_return_rounded,
    TaskCategory.pickup => Icons.shopping_bag_rounded,
    TaskCategory.delivery => Icons.local_shipping_rounded,
    TaskCategory.cooking => Icons.soup_kitchen_rounded,
    TaskCategory.breakfast => Icons.free_breakfast_rounded,
    TaskCategory.lunch || TaskCategory.dinner => Icons.restaurant_rounded,
    TaskCategory.restaurant => Icons.ramen_dining_rounded,
    TaskCategory.coffee => Icons.coffee_rounded,
    TaskCategory.foodOrder => Icons.delivery_dining_rounded,
    TaskCategory.mealPrep => Icons.lunch_dining_rounded,
    TaskCategory.baking => Icons.bakery_dining_rounded,
    TaskCategory.drinks => Icons.local_cafe_rounded,
    TaskCategory.health => Icons.favorite_rounded,
    TaskCategory.doctor => Icons.medical_services_rounded,
    TaskCategory.dentist => Icons.sentiment_very_satisfied_rounded,
    TaskCategory.medicine => Icons.medication_rounded,
    TaskCategory.pharmacy => Icons.local_pharmacy_rounded,
    TaskCategory.hospital => Icons.local_hospital_rounded,
    TaskCategory.therapy => Icons.psychology_rounded,
    TaskCategory.checkup => Icons.monitor_heart_rounded,
    TaskCategory.vaccination => Icons.vaccines_rounded,
    TaskCategory.medicalTest => Icons.biotech_rounded,
    TaskCategory.meditation => Icons.self_improvement_rounded,
    TaskCategory.gym || TaskCategory.workout => Icons.fitness_center_rounded,
    TaskCategory.running => Icons.directions_run_rounded,
    TaskCategory.walking => Icons.directions_walk_rounded,
    TaskCategory.cycling => Icons.pedal_bike_rounded,
    TaskCategory.swimming => Icons.pool_rounded,
    TaskCategory.yoga ||
    TaskCategory.stretching => Icons.self_improvement_rounded,
    TaskCategory.sport => Icons.sports_soccer_rounded,
    TaskCategory.travel => Icons.travel_explore_rounded,
    TaskCategory.flight => Icons.flight_rounded,
    TaskCategory.hotel => Icons.hotel_rounded,
    TaskCategory.vacation => Icons.beach_access_rounded,
    TaskCategory.luggage => Icons.luggage_rounded,
    TaskCategory.passport => Icons.badge_rounded,
    TaskCategory.visa => Icons.approval_rounded,
    TaskCategory.tripPlanning => Icons.flight_takeoff_rounded,
    TaskCategory.sightseeing => Icons.photo_camera_rounded,
    TaskCategory.reservation => Icons.book_online_rounded,
    TaskCategory.car => Icons.directions_car_rounded,
    TaskCategory.carMaintenance ||
    TaskCategory.carRepair => Icons.car_repair_rounded,
    TaskCategory.fuel => Icons.local_gas_station_rounded,
    TaskCategory.carWash => Icons.local_car_wash_rounded,
    TaskCategory.parking => Icons.local_parking_rounded,
    TaskCategory.publicTransport => Icons.directions_bus_rounded,
    TaskCategory.taxi => Icons.local_taxi_rounded,
    TaskCategory.train => Icons.train_rounded,
    TaskCategory.driving => Icons.route_rounded,
    TaskCategory.home => Icons.home_rounded,
    TaskCategory.cleaning => Icons.cleaning_services_rounded,
    TaskCategory.laundry => Icons.local_laundry_service_rounded,
    TaskCategory.dishes => Icons.countertops_rounded,
    TaskCategory.homeRepair => Icons.handyman_rounded,
    TaskCategory.gardening => Icons.yard_rounded,
    TaskCategory.furniture => Icons.chair_rounded,
    TaskCategory.moving => Icons.inventory_2_rounded,
    TaskCategory.organizing => Icons.auto_awesome_mosaic_rounded,
    TaskCategory.bills => Icons.receipt_long_rounded,
    TaskCategory.finance => Icons.savings_rounded,
    TaskCategory.payment => Icons.payments_rounded,
    TaskCategory.banking => Icons.account_balance_rounded,
    TaskCategory.subscription => Icons.subscriptions_rounded,
    TaskCategory.family => Icons.family_restroom_rounded,
    TaskCategory.friends => Icons.diversity_1_rounded,
    TaskCategory.pet => Icons.pets_rounded,
    TaskCategory.entertainment => Icons.movie_filter_rounded,
    TaskCategory.appointment => Icons.event_available_rounded,
    TaskCategory.other => fallback,
  };

  static Color colorFor(TaskCategory category) => switch (category) {
    TaskCategory.work => const Color(0xFF5B6CFF),
    TaskCategory.meeting => const Color(0xFF7C5CFF),
    TaskCategory.presentation => const Color(0xFF4E8CFF),
    TaskCategory.email => const Color(0xFF3D9BFF),
    TaskCategory.phoneCall => const Color(0xFF2BB4A8),
    TaskCategory.project => const Color(0xFF6A7CFF),
    TaskCategory.deadline => const Color(0xFFFF6B6B),
    TaskCategory.coding => const Color(0xFF5B8DEF),
    TaskCategory.bugFix => const Color(0xFFFF7A59),
    TaskCategory.research => const Color(0xFF4EA0FF),
    TaskCategory.study => const Color(0xFF4E8CFF),
    TaskCategory.homework => const Color(0xFF6C8CFF),
    TaskCategory.exam => const Color(0xFFFF8A3D),
    TaskCategory.reading => const Color(0xFF5B8CFF),
    TaskCategory.writing => const Color(0xFF7B6CFF),
    TaskCategory.noteTaking => const Color(0xFFFFB020),
    TaskCategory.languageLearning => const Color(0xFF3DB8E8),
    TaskCategory.school => const Color(0xFF4E8CFF),
    TaskCategory.childcare => const Color(0xFFFF8AB5),
    TaskCategory.sleep => const Color(0xFF7B6CFF),
    TaskCategory.shopping => const Color(0xFFFF6B9D),
    TaskCategory.groceries => const Color(0xFF3ECF8E),
    TaskCategory.clothesShopping => const Color(0xFFFF7AB5),
    TaskCategory.electronicsShopping => const Color(0xFF5B8CFF),
    TaskCategory.onlineOrder => const Color(0xFFFF8A3D),
    TaskCategory.gift => const Color(0xFFFF5D8F),
    TaskCategory.birthday => const Color(0xFFFF7A9C),
    TaskCategory.returnItem => const Color(0xFF8B90A7),
    TaskCategory.pickup => const Color(0xFFFF8A3D),
    TaskCategory.delivery => const Color(0xFF3DB8E8),
    TaskCategory.cooking => const Color(0xFFFF8A3D),
    TaskCategory.breakfast => const Color(0xFFFFB020),
    TaskCategory.lunch => const Color(0xFFFF8A3D),
    TaskCategory.dinner => const Color(0xFFFF6B4A),
    TaskCategory.restaurant => const Color(0xFFFF7A3D),
    TaskCategory.coffee => const Color(0xFFC4845A),
    TaskCategory.foodOrder => const Color(0xFFFF7A59),
    TaskCategory.mealPrep => const Color(0xFF3ECF8E),
    TaskCategory.baking => const Color(0xFFFF9A62),
    TaskCategory.drinks => const Color(0xFF5B8CFF),
    TaskCategory.health => const Color(0xFFFF6B8A),
    TaskCategory.doctor => const Color(0xFF3ECF8E),
    TaskCategory.dentist => const Color(0xFF3DB8E8),
    TaskCategory.medicine => const Color(0xFF4EA0FF),
    TaskCategory.pharmacy => const Color(0xFF3ECF8E),
    TaskCategory.hospital => const Color(0xFFFF6B6B),
    TaskCategory.therapy => const Color(0xFF9B7BFF),
    TaskCategory.checkup => const Color(0xFFFF6B8A),
    TaskCategory.vaccination => const Color(0xFF3DB8E8),
    TaskCategory.medicalTest => const Color(0xFF2BB4A8),
    TaskCategory.meditation => const Color(0xFF9B7BFF),
    TaskCategory.gym => const Color(0xFFFF5D6C),
    TaskCategory.workout => const Color(0xFFFF5D6C),
    TaskCategory.running => const Color(0xFFFF5D4C),
    TaskCategory.walking => const Color(0xFF3DB89A),
    TaskCategory.cycling => const Color(0xFF3D9BFF),
    TaskCategory.swimming => const Color(0xFF3DB8E8),
    TaskCategory.yoga => const Color(0xFF9B7BFF),
    TaskCategory.stretching => const Color(0xFF7C5CFF),
    TaskCategory.sport => const Color(0xFF3ECF8E),
    TaskCategory.travel => const Color(0xFF3DB8E8),
    TaskCategory.flight => const Color(0xFF4E8CFF),
    TaskCategory.hotel => const Color(0xFF7B6CFF),
    TaskCategory.vacation => const Color(0xFFFFB020),
    TaskCategory.luggage => const Color(0xFF5B8CFF),
    TaskCategory.passport => const Color(0xFF4E8CFF),
    TaskCategory.visa => const Color(0xFF2BB4A8),
    TaskCategory.tripPlanning => const Color(0xFF5B6CFF),
    TaskCategory.sightseeing => const Color(0xFFFF7A9C),
    TaskCategory.reservation => const Color(0xFF7C5CFF),
    TaskCategory.car => const Color(0xFF5C7CFA),
    TaskCategory.carMaintenance => const Color(0xFF8B90A7),
    TaskCategory.carRepair => const Color(0xFFFF8A3D),
    TaskCategory.fuel => const Color(0xFFFF6B4A),
    TaskCategory.carWash => const Color(0xFF3DB8E8),
    TaskCategory.parking => const Color(0xFF5B6CFF),
    TaskCategory.publicTransport => const Color(0xFF4E8CFF),
    TaskCategory.taxi => const Color(0xFFFFB020),
    TaskCategory.train => const Color(0xFF5B6CFF),
    TaskCategory.driving => const Color(0xFF2BB4A8),
    TaskCategory.home => const Color(0xFFFFB020),
    TaskCategory.cleaning => const Color(0xFF3DB8E8),
    TaskCategory.laundry => const Color(0xFF7C5CFF),
    TaskCategory.dishes => const Color(0xFF3DB89A),
    TaskCategory.homeRepair => const Color(0xFFFF8A3D),
    TaskCategory.gardening => const Color(0xFF3ECF8E),
    TaskCategory.furniture => const Color(0xFFC4845A),
    TaskCategory.moving => const Color(0xFF5B8CFF),
    TaskCategory.organizing => const Color(0xFFFF9A62),
    TaskCategory.bills => const Color(0xFF2BB673),
    TaskCategory.finance => const Color(0xFF2BB673),
    TaskCategory.payment => const Color(0xFF3ECF8E),
    TaskCategory.banking => const Color(0xFF2BB4A8),
    TaskCategory.subscription => const Color(0xFF7C5CFF),
    TaskCategory.family => const Color(0xFFFF7A9C),
    TaskCategory.friends => const Color(0xFFFF8AB5),
    TaskCategory.pet => const Color(0xFFFF9A62),
    TaskCategory.entertainment => const Color(0xFF9B7BFF),
    TaskCategory.appointment => const Color(0xFF5B6CFF),
    TaskCategory.other => const Color(0xFF7C84A3),
  };

  static Color colorForName(String name) {
    final category = taskCategoryByStorageName[name];
    if (category != null) return colorFor(category);
    const palette = [
      Color(0xFF5B6CFF),
      Color(0xFFFF6B9D),
      Color(0xFF3ECF8E),
      Color(0xFFFF8A3D),
      Color(0xFF3DB8E8),
      Color(0xFF9B7BFF),
    ];
    return palette[name.hashCode.abs() % palette.length];
  }

  static IconData fromStorageName(String name) {
    final category = taskCategoryByStorageName[name];
    return category == null ? fallback : iconFor(category);
  }
}
