import 'package:flutter/material.dart';
import 'package:florien/features/task_icon/domain/task_category.dart';

class TaskIconMapper {
  const TaskIconMapper._();

  static const fallback = Icons.task_alt_rounded;

  static IconData iconFor(TaskCategory category) => switch (category) {
    TaskCategory.work => Icons.work_outline_rounded,
    TaskCategory.meeting => Icons.groups_rounded,
    TaskCategory.presentation => Icons.slideshow_rounded,
    TaskCategory.email => Icons.email_outlined,
    TaskCategory.phoneCall => Icons.call_outlined,
    TaskCategory.project => Icons.account_tree_outlined,
    TaskCategory.deadline => Icons.event_busy_outlined,
    TaskCategory.coding => Icons.code_rounded,
    TaskCategory.bugFix => Icons.bug_report_outlined,
    TaskCategory.research => Icons.manage_search_rounded,
    TaskCategory.study => Icons.school_outlined,
    TaskCategory.homework => Icons.assignment_outlined,
    TaskCategory.exam => Icons.quiz_outlined,
    TaskCategory.reading => Icons.menu_book_rounded,
    TaskCategory.writing => Icons.edit_note_rounded,
    TaskCategory.noteTaking => Icons.note_alt_outlined,
    TaskCategory.languageLearning => Icons.translate_rounded,
    TaskCategory.school => Icons.school_rounded,
    TaskCategory.childcare => Icons.child_care_rounded,
    TaskCategory.sleep => Icons.bedtime_outlined,
    TaskCategory.shopping => Icons.shopping_bag_outlined,
    TaskCategory.groceries => Icons.local_grocery_store_outlined,
    TaskCategory.clothesShopping => Icons.checkroom_outlined,
    TaskCategory.electronicsShopping => Icons.devices_other_outlined,
    TaskCategory.onlineOrder => Icons.shopping_cart_checkout_rounded,
    TaskCategory.gift => Icons.card_giftcard_rounded,
    TaskCategory.birthday => Icons.cake_outlined,
    TaskCategory.returnItem => Icons.assignment_return_outlined,
    TaskCategory.pickup => Icons.shopping_bag_rounded,
    TaskCategory.delivery => Icons.local_shipping_outlined,
    TaskCategory.cooking => Icons.kitchen_outlined,
    TaskCategory.breakfast => Icons.free_breakfast_outlined,
    TaskCategory.lunch || TaskCategory.dinner => Icons.restaurant_outlined,
    TaskCategory.restaurant => Icons.restaurant_menu_rounded,
    TaskCategory.coffee => Icons.coffee_outlined,
    TaskCategory.foodOrder => Icons.delivery_dining_outlined,
    TaskCategory.mealPrep => Icons.lunch_dining_outlined,
    TaskCategory.baking => Icons.bakery_dining_outlined,
    TaskCategory.drinks => Icons.local_drink_outlined,
    TaskCategory.health => Icons.health_and_safety_outlined,
    TaskCategory.doctor => Icons.medical_services_outlined,
    TaskCategory.dentist => Icons.medical_services_outlined,
    TaskCategory.medicine => Icons.medication_outlined,
    TaskCategory.pharmacy => Icons.local_pharmacy_outlined,
    TaskCategory.hospital => Icons.local_hospital_outlined,
    TaskCategory.therapy => Icons.psychology_alt_outlined,
    TaskCategory.checkup => Icons.monitor_heart_outlined,
    TaskCategory.vaccination => Icons.vaccines_outlined,
    TaskCategory.medicalTest => Icons.biotech_outlined,
    TaskCategory.meditation => Icons.self_improvement_rounded,
    TaskCategory.gym || TaskCategory.workout => Icons.fitness_center_rounded,
    TaskCategory.running => Icons.directions_run_rounded,
    TaskCategory.walking => Icons.directions_walk_rounded,
    TaskCategory.cycling => Icons.directions_bike_rounded,
    TaskCategory.swimming => Icons.pool_outlined,
    TaskCategory.yoga ||
    TaskCategory.stretching => Icons.self_improvement_outlined,
    TaskCategory.sport => Icons.sports_basketball_outlined,
    TaskCategory.travel => Icons.travel_explore_rounded,
    TaskCategory.flight => Icons.flight_rounded,
    TaskCategory.hotel => Icons.hotel_outlined,
    TaskCategory.vacation => Icons.beach_access_outlined,
    TaskCategory.luggage => Icons.luggage_outlined,
    TaskCategory.passport => Icons.badge_outlined,
    TaskCategory.visa => Icons.approval_outlined,
    TaskCategory.tripPlanning => Icons.flight_takeoff_rounded,
    TaskCategory.sightseeing => Icons.photo_camera_outlined,
    TaskCategory.reservation => Icons.book_online_outlined,
    TaskCategory.car => Icons.directions_car_outlined,
    TaskCategory.carMaintenance ||
    TaskCategory.carRepair => Icons.car_repair_rounded,
    TaskCategory.fuel => Icons.local_gas_station_outlined,
    TaskCategory.carWash => Icons.local_car_wash_outlined,
    TaskCategory.parking => Icons.local_parking_rounded,
    TaskCategory.publicTransport => Icons.directions_transit_outlined,
    TaskCategory.taxi => Icons.local_taxi_outlined,
    TaskCategory.train => Icons.train_outlined,
    TaskCategory.driving => Icons.route_outlined,
    TaskCategory.home => Icons.home_outlined,
    TaskCategory.cleaning => Icons.cleaning_services_outlined,
    TaskCategory.laundry => Icons.local_laundry_service_outlined,
    TaskCategory.dishes => Icons.countertops_outlined,
    TaskCategory.homeRepair => Icons.handyman_outlined,
    TaskCategory.gardening => Icons.yard_outlined,
    TaskCategory.furniture => Icons.chair_outlined,
    TaskCategory.moving => Icons.move_up_outlined,
    TaskCategory.organizing => Icons.inventory_2_outlined,
    TaskCategory.bills => Icons.receipt_long_outlined,
    TaskCategory.finance => Icons.account_balance_wallet_outlined,
    TaskCategory.payment => Icons.payments_outlined,
    TaskCategory.banking => Icons.account_balance_outlined,
    TaskCategory.subscription => Icons.subscriptions_outlined,
    TaskCategory.family => Icons.family_restroom_rounded,
    TaskCategory.friends => Icons.people_outline_rounded,
    TaskCategory.pet => Icons.pets_outlined,
    TaskCategory.entertainment => Icons.movie_outlined,
    TaskCategory.appointment => Icons.event_available_outlined,
    TaskCategory.other => fallback,
  };

  static IconData fromStorageName(String name) {
    final category = taskCategoryByStorageName[name];
    return category == null ? fallback : iconFor(category);
  }
}
