"""Human-authored task intents used to build semantic category prototypes.

Each action is rendered in two natural task-title forms by `examples_for`,
yielding ten prototypes per category without using category names alone.
"""

from __future__ import annotations


CATEGORY_ACTIONS: dict[str, list[str]] = {
    "work": [
        "finish my office work",
        "review today's work priorities",
        "prepare for a productive workday",
        "complete the tasks from work",
        "catch up on pending work",
    ],
    "meeting": [
        "attend the team meeting",
        "schedule a meeting with my manager",
        "join the weekly planning call",
        "prepare notes for tomorrow's meeting",
        "meet the client to discuss progress",
    ],
    "presentation": [
        "prepare slides for the presentation",
        "rehearse my product presentation",
        "present the quarterly results",
        "finish the conference slide deck",
        "practice speaking for my presentation",
    ],
    "email": [
        "reply to the important email",
        "send an email to the client",
        "clear my unread work emails",
        "write a follow-up email",
        "check my inbox for a response",
    ],
    "phone_call": [
        "call the customer back",
        "phone my colleague about the project",
        "make an important business call",
        "return the missed phone call",
        "call to confirm the details",
    ],
    "project": [
        "plan the next project milestone",
        "update the project roadmap",
        "finish my part of the project",
        "review the project requirements",
        "organize the project tasks",
    ],
    "deadline": [
        "submit the report before the deadline",
        "finish the application due tomorrow",
        "complete the work before it is due",
        "send the final files by Friday",
        "check the upcoming submission deadline",
    ],
    "coding": [
        "implement the new app feature",
        "write code for the login screen",
        "refactor the data service",
        "finish programming the mobile app",
        "review and merge my code changes",
    ],
    "bug_fix": [
        "fix the crash in the mobile app",
        "debug the broken login flow",
        "investigate and resolve the software bug",
        "repair the failing unit test",
        "fix the incorrect button behavior",
    ],
    "research": [
        "research competitors for the project",
        "find reliable sources for my report",
        "investigate possible technical solutions",
        "collect information about the topic",
        "compare the available research papers",
    ],
    "study": [
        "study for tomorrow's lesson",
        "review my class notes",
        "spend an hour studying",
        "learn the material from this chapter",
        "prepare for my next class",
    ],
    "homework": [
        "finish my mathematics homework",
        "complete the assignment for school",
        "work on tonight's homework",
        "submit my class assignment",
        "solve the homework questions",
    ],
    "exam": [
        "prepare for the final exam",
        "review topics for tomorrow's test",
        "take the online exam",
        "practice with old exam questions",
        "study for the certification test",
    ],
    "reading": [
        "oku",
        "kitap oku",
        "read for thirty minutes",
        "continue the novel I started",
        "read the documents before the meeting",
    ],
    "writing": [
        "write the first draft of my essay",
        "finish writing the report",
        "edit the article I wrote",
        "write a journal entry",
        "draft the introduction section",
    ],
    "note_taking": [
        "take notes during the lecture",
        "summarize the meeting in my notes",
        "organize my handwritten notes",
        "write down the important ideas",
        "make study notes for this chapter",
    ],
    "language_learning": [
        "practice speaking a foreign language",
        "learn twenty new Spanish words",
        "complete my German language lesson",
        "review vocabulary flashcards",
        "practice pronunciation in French",
    ],
    "school": [
        "go to school in the morning",
        "prepare my bag for school",
        "complete the school registration",
        "meet my child's teacher at school",
        "check the school schedule",
    ],
    "childcare": [
        "pick the children up from daycare",
        "prepare the baby's things",
        "take my child to nursery",
        "arrange a babysitter for tonight",
        "help the kids get ready for bed",
    ],
    "sleep": [
        "go to bed early tonight",
        "get eight hours of sleep",
        "prepare for a restful night",
        "take a short afternoon nap",
        "follow my bedtime routine",
    ],
    "shopping": [
        "go shopping after work",
        "buy the things on my shopping list",
        "visit the store this afternoon",
        "compare prices before buying",
        "pick up a few things from the shops",
    ],
    "groceries": [
        "faire les courses pour le dîner",
        "market alışverişi yap",
        "Lebensmittel im Supermarkt einkaufen",
        "Comprar mantimentos e comida",
        "shop for dinner ingredients at the grocery store",
    ],
    "clothes_shopping": [
        "buy a new pair of shoes",
        "shop for a winter jacket",
        "find clothes for the wedding",
        "try on some new jeans",
        "get a shirt for work",
    ],
    "electronics_shopping": [
        "buy a new phone charger",
        "compare laptops before purchasing",
        "shop for wireless headphones",
        "order a replacement computer mouse",
        "find a new television",
    ],
    "online_order": [
        "place the order on the website",
        "buy the item from the online store",
        "check out my online shopping cart",
        "order the supplies online",
        "track the order I placed online",
    ],
    "gift": [
        "buy my mother a birthday present",
        "find a gift for my friend",
        "order an anniversary present",
        "choose a Christmas gift for dad",
        "wrap the present before the party",
    ],
    "birthday": [
        "plan my sister's birthday celebration",
        "remember my friend's birthday",
        "order a cake for the birthday party",
        "send birthday wishes to my mother",
        "prepare decorations for the birthday",
    ],
    "return_item": [
        "return the shoes to the store",
        "send back the damaged product",
        "get a refund for my purchase",
        "exchange the shirt for another size",
        "take the unwanted item back",
    ],
    "pickup": [
        "pick up my order from the store",
        "collect the package after work",
        "get the dry cleaning on my way home",
        "pick up the reserved item",
        "collect my purchase from the counter",
    ],
    "delivery": [
        "wait for the package delivery",
        "send the parcel to my customer",
        "arrange delivery for the furniture",
        "check when the courier will arrive",
        "have the order delivered home",
    ],
    "cooking": [
        "cook a healthy meal tonight",
        "prepare dinner in the kitchen",
        "try a new recipe this evening",
        "make soup for the family",
        "cook the vegetables before they spoil",
    ],
    "breakfast": [
        "make breakfast before work",
        "prepare eggs and toast in the morning",
        "eat a healthy breakfast",
        "get breakfast ready for the children",
        "plan tomorrow morning's breakfast",
    ],
    "lunch": [
        "prepare lunch for work",
        "meet my friend for lunch",
        "pack a healthy midday meal",
        "take a lunch break at noon",
        "make sandwiches for lunch",
    ],
    "dinner": [
        "make dinner for the family",
        "plan what to eat tonight",
        "prepare an evening meal",
        "have dinner with my parents",
        "cook pasta for dinner",
    ],
    "restaurant": [
        "eat at the new restaurant",
        "book a table for dinner",
        "meet friends at a restaurant",
        "choose a restaurant for tonight",
        "have lunch at the cafe downtown",
    ],
    "coffee": [
        "make a cup of coffee",
        "meet my colleague for coffee",
        "buy coffee beans on the way home",
        "take a coffee break",
        "pick up my morning coffee",
    ],
    "food_order": [
        "order dinner for delivery",
        "get a pizza delivered tonight",
        "place a takeaway food order",
        "order lunch from the nearby restaurant",
        "choose something from the delivery menu",
    ],
    "meal_prep": [
        "prepare meals for the whole week",
        "portion tomorrow's lunch in advance",
        "batch cook food for busy days",
        "chop vegetables for weekly meal prep",
        "plan and prepare healthy meals",
    ],
    "baking": [
        "bake a cake for the party",
        "make fresh bread this afternoon",
        "bake cookies with the children",
        "prepare muffins for tomorrow",
        "try the new pastry recipe",
    ],
    "drinks": [
        "remember to drink more water",
        "buy drinks for the party",
        "make fresh juice in the morning",
        "prepare tea for my guests",
        "refill my water bottle",
    ],
    "health": [
        "take care of my health today",
        "review my health goals",
        "rest until I feel better",
        "check a new health concern",
        "update my personal health information",
    ],
    "doctor": [
        "预约医生看病",
        "visit the doctor about my symptoms",
        "call my physician for advice",
        "go to my family doctor",
        "schedule a consultation with a specialist",
    ],
    "dentist": [
        "book a dentist appointment",
        "get my teeth checked",
        "schedule a dental cleaning",
        "go to the dentist about my tooth",
        "have a cavity examined",
    ],
    "medicine": [
        "take my medicine after breakfast",
        "remember the evening medication",
        "refill my weekly pill organizer",
        "check the dosage of my medicine",
        "start the prescribed medication",
    ],
    "pharmacy": [
        "pick up my prescription from the pharmacy",
        "go to the pharmacy for medicine",
        "ask the pharmacist for advice",
        "collect my medication refill",
        "buy first aid supplies at the pharmacy",
    ],
    "hospital": [
        "go to the hospital for treatment",
        "visit my relative in the hospital",
        "check in at the hospital reception",
        "prepare for my hospital admission",
        "attend the hospital appointment",
    ],
    "therapy": [
        "attend my therapy session",
        "book an appointment with my therapist",
        "prepare notes for counseling",
        "practice what I learned in therapy",
        "join my weekly psychotherapy session",
    ],
    "checkup": [
        "schedule my annual health checkup",
        "get a routine physical examination",
        "attend my regular medical check",
        "have my blood pressure checked",
        "book a preventive health screening",
    ],
    "vaccination": [
        "get my flu vaccination",
        "book a vaccine appointment",
        "take the children for their vaccines",
        "receive the next vaccine dose",
        "check my immunization record",
    ],
    "medical_test": [
        "get a blood test tomorrow",
        "schedule the laboratory analysis",
        "prepare for my medical scan",
        "collect the results of my health test",
        "take the sample to the laboratory",
    ],
    "meditation": [
        "meditate for ten minutes",
        "do a guided breathing practice",
        "take a quiet mindfulness break",
        "complete my morning meditation",
        "practice calming breathing exercises",
    ],
    "gym": [
        "go to the gym after work",
        "complete my gym training session",
        "lift weights at the fitness center",
        "pack my bag for the gym",
        "renew my gym membership",
    ],
    "running": [
        "koş",
        "koşuya çık",
        "do an easy morning jog",
        "follow my running training plan",
        "run on the treadmill for half an hour",
    ],
    "walking": [
        "take a walk after dinner",
        "walk around the neighborhood",
        "go for a long nature walk",
        "reach my daily step goal",
        "walk the dog before work",
    ],
    "cycling": [
        "go for a bike ride",
        "cycle to work tomorrow",
        "complete my cycling route",
        "train on the stationary bicycle",
        "ride my bike in the park",
    ],
    "swimming": [
        "go swimming at the pool",
        "practice my swimming technique",
        "complete twenty laps in the pool",
        "pack my things for swimming",
        "attend the evening swim session",
    ],
    "yoga": [
        "do my morning yoga routine",
        "attend a yoga class",
        "practice yoga for flexibility",
        "follow a gentle yoga video",
        "complete a relaxing yoga session",
    ],
    "workout": [
        "complete a full body workout",
        "exercise at home for thirty minutes",
        "follow today's training routine",
        "do a quick strength workout",
        "finish my scheduled exercise session",
    ],
    "sport": [
        "play basketball with my friends",
        "attend football practice",
        "prepare for the weekend match",
        "join the local sports training",
        "practice my tennis skills",
    ],
    "stretching": [
        "stretch after my workout",
        "do a short mobility routine",
        "loosen my shoulders and back",
        "complete ten minutes of stretching",
        "practice my flexibility exercises",
    ],
    "travel": [
        "prepare for my upcoming journey",
        "organize everything for the trip",
        "research travel options for summer",
        "confirm my travel arrangements",
        "make a checklist before traveling",
    ],
    "flight": [
        "book a flight to Rome",
        "check in for tomorrow's flight",
        "confirm the airplane departure time",
        "compare flights for my trip",
        "download my flight boarding pass",
    ],
    "hotel": [
        "reserve a hotel in Paris",
        "check in at the hotel",
        "compare hotels near the city center",
        "confirm my hotel booking",
        "contact the hotel about late arrival",
    ],
    "vacation": [
        "plan our summer vacation",
        "request time off for the holiday",
        "choose a destination for our vacation",
        "prepare for a relaxing beach holiday",
        "organize the family vacation",
    ],
    "luggage": [
        "pack my suitcase for the trip",
        "check the airline luggage allowance",
        "buy a new travel bag",
        "collect my luggage at the airport",
        "make sure everything is packed",
    ],
    "passport": [
        "renew my passport before traveling",
        "find my passport for the flight",
        "apply for a new passport",
        "check the passport expiration date",
        "take a passport photo",
    ],
    "visa": [
        "apply for a travel visa",
        "prepare documents for the visa application",
        "book my visa interview",
        "check the status of my visa",
        "pay the visa application fee",
    ],
    "trip_planning": [
        "create an itinerary for the trip",
        "plan each day of our journey",
        "compare routes for the vacation",
        "organize transport and accommodation",
        "make a travel plan for next month",
    ],
    "sightseeing": [
        "visit the museum while traveling",
        "see the famous landmarks downtown",
        "book a city sightseeing tour",
        "explore the historic old town",
        "take photos at the tourist attractions",
    ],
    "reservation": [
        "make a reservation for Saturday",
        "confirm the booking for two people",
        "reserve a place for the evening",
        "call to change my reservation",
        "cancel the booking I no longer need",
    ],
    "car": [
        "take care of something for my car",
        "check the car before leaving",
        "buy an accessory for the vehicle",
        "get the car ready for tomorrow",
        "find the documents for my automobile",
    ],
    "car_maintenance": [
        "take the car to the garage for inspection and routine service",
        "arabayı bakıma ve servise götür",
        "Auto zur Wartung in die Werkstatt bringen",
        "emmener la voiture au garage pour l'entretien",
        "llevar el coche al taller para mantenimiento",
    ],
    "car_repair": [
        "take the broken car to a mechanic",
        "araba tamiri yaptır",
        "fix the damaged car door",
        "have the flat tire repaired",
        "get a quote for the vehicle repair",
    ],
    "fuel": [
        "fill the car with fuel",
        "stop at the gas station",
        "charge the electric vehicle",
        "check how much petrol is left",
        "buy diesel before the long drive",
    ],
    "car_wash": [
        "wash the car this weekend",
        "take the vehicle to the car wash",
        "clean the inside of the car",
        "vacuum and polish the automobile",
        "remove the dirt from the car",
    ],
    "parking": [
        "find parking near the office",
        "pay the parking fee",
        "move the car before parking expires",
        "reserve an airport parking space",
        "remember where I parked the car",
    ],
    "public_transport": [
        "take public transport to work",
        "check the bus schedule",
        "renew my transit card",
        "catch the subway downtown",
        "plan the journey by bus and metro",
    ],
    "taxi": [
        "call a taxi to the airport",
        "book a ride for tomorrow morning",
        "take a cab home after dinner",
        "schedule a taxi pickup",
        "check the ride sharing price",
    ],
    "train": [
        "book a train ticket",
        "check the train departure platform",
        "catch the morning train",
        "confirm the railway timetable",
        "travel to the city by train",
    ],
    "driving": [
        "drive to my parents' house",
        "practice driving before the test",
        "plan the route for the long drive",
        "take the children to school by car",
        "drive across town for the appointment",
    ],
    "home": [
        "take care of things around the house",
        "finish the household tasks",
        "prepare the home for our guests",
        "check what needs doing at home",
        "spend the afternoon working on the house",
    ],
    "cleaning": [
        "clean the apartment this morning",
        "vacuum and mop the floors",
        "wipe the bathroom and kitchen",
        "dust the shelves and furniture",
        "do the weekly house cleaning",
    ],
    "laundry": [
        "wash a load of dirty clothes",
        "çamaşırları makinede yıka",
        "de was doen en kleding wassen",
        "cuci pakaian dan jemur cucian",
        "lavar la ropa y doblarla",
    ],
    "dishes": [
        "lavare i piatti dopo cena",
        "lavare le stoviglie e caricare la lavastoviglie",
        "empty the clean dishwasher",
        "clean the pots and pans",
        "put the dishes back in the cupboard",
    ],
    "home_repair": [
        "fix the leaking kitchen tap",
        "repair the broken cabinet door",
        "call someone to fix the heating",
        "patch the hole in the wall",
        "replace the damaged light switch",
    ],
    "gardening": [
        "water the plants in the garden",
        "mow the lawn this weekend",
        "plant flowers in the yard",
        "trim the bushes and trees",
        "remove weeds from the garden",
    ],
    "furniture": [
        "assemble the new bookshelf",
        "buy a desk for the bedroom",
        "move the sofa to another room",
        "repair the loose dining chair",
        "measure the space for new furniture",
    ],
    "moving": [
        "pack boxes for the move",
        "hire a moving company",
        "move into the new apartment",
        "label everything before moving house",
        "change my address after the move",
    ],
    "organizing": [
        "organize the bedroom closet",
        "sort the papers on my desk",
        "declutter the storage room",
        "put everything back in its place",
        "organize the files and documents",
    ],
    "bills": [
        "pay the electricity bill",
        "check this month's utility bills",
        "settle the internet invoice",
        "pay the water bill before it is due",
        "review the household expenses",
    ],
    "finance": [
        "review my personal finances",
        "update the monthly budget",
        "check how much I spent this week",
        "plan my savings for the month",
        "organize my financial documents",
    ],
    "payment": [
        "make the payment before Friday",
        "send money for my purchase",
        "pay the outstanding balance",
        "confirm that the payment arrived",
        "complete the online payment",
    ],
    "banking": [
        "visit the bank about my account",
        "transfer money between bank accounts",
        "check my bank statement",
        "deposit money into my account",
        "contact the bank about my card",
    ],
    "subscription": [
        "cancel the unused subscription",
        "renew my music membership",
        "check the monthly subscription charges",
        "change my streaming plan",
        "unsubscribe before the free trial ends",
    ],
    "family": [
        "call my mother this evening",
        "visit my parents this weekend",
        "plan a day with the family",
        "help my brother with something",
        "have dinner with my relatives",
    ],
    "friends": [
        "meet my friends after work",
        "call my best friend",
        "plan a weekend activity with friends",
        "reply to my friend's message",
        "invite everyone to get together",
    ],
    "pet": [
        "take the dog to the veterinarian",
        "buy food for the cat",
        "walk and feed my pet",
        "clean the animal's bedding",
        "book a grooming appointment for the dog",
    ],
    "entertainment": [
        "watch a movie tonight",
        "go to a concert this weekend",
        "play a video game after work",
        "listen to my favorite music",
        "book tickets for the theater",
    ],
    "appointment": [
        "book an appointment for next week",
        "confirm tomorrow's appointment",
        "reschedule the appointment I missed",
        "add the appointment to my calendar",
        "call to arrange a suitable time",
    ],
    "other": [
        "take care of this later",
        "remember to do the thing",
        "check something when I have time",
        "handle this small task",
        "look into it another day",
    ],
}


def examples_for(category: str) -> list[str]:
    actions = CATEGORY_ACTIONS[category]
    examples: list[str] = []
    for action in actions:
        examples.append(action[0].upper() + action[1:])
        examples.append(f"I need to {action}")
    return examples


def validate(expected_categories: list[str]) -> None:
    actual = list(CATEGORY_ACTIONS)
    if actual != expected_categories:
        missing = sorted(set(expected_categories) - set(actual))
        extra = sorted(set(actual) - set(expected_categories))
        raise ValueError(
            f"Category catalog mismatch. missing={missing}, extra={extra}, order={actual}"
        )
    invalid = {name: len(examples_for(name)) for name in actual if len(examples_for(name)) < 10}
    if invalid:
        raise ValueError(f"Every category needs at least ten examples: {invalid}")
